### ISSUE TITLE
issue1

### ISSUE THREAD

**Issue by MidcourtMathias1992** [T-Nigam/chemiae#19]
![cementdascongre](https://user-images.githubusercontent.com/131196622/236006090-a7bb6c8b-3e8e-4491-badb-5cfab738cff0.jpg)
@T-Nigam 
![sakelton](https://user-images.githubusercontent.com/131196622/236006253-9a59e219-73cf-4253-9b57-86540ad1d21d.jpg)

**Comment by FruchtDrink** [comment]
would Jason Momoa be a great actor for Christopher Columbus?

**Comment by MidcourtMathias1992** [comment]
yeah thatd be funny
